apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: data-platform
type: Opaque
data:
  username: cG9zdGdyZXM=       # postgres
  password: cG9zdGdyZXM=       # postgres
  database: cHJvZHVjZXJfZGI=   # producer_db
