apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: data-platform
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30942
      name: http
  selector:
    app: producer
